swiftmailer:
    default_mailer: mibukyos
    mailers:
        mibukyos:
            transport: gmail
            username: mibukyos@gmail.com
            password: dGhpZXJyeXNpb24=
            # sender_address: ~
            # delivery_addresses: ~
            disable_delivery: false

#    url: '%env(MAILER_URL)%'
#    spool: { type: 'memory' }
